language: cpp

os:
 - osx
 
osx_image: xcode6.4

compiler:
 - clang
 
before_script:
 - mkdir build
 - cd build
 
script:
 - cmake ..
 - make -j 4
 
after_success:
 - cat ./cmake/modules/CMakeFiles/LLVMConfig.cmake
 - ls */
