language: cpp

os:
 - osx
 
osx_image: xcode6.4

compiler:
 - clang
 
before_script:
 - mkdir build
 - cd build
 
script:
 - cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 ..
 - make -j 4
 
after_success:
 - cat ./cmake/modules/CMakeFiles/LLVMConfig.cmake
 - ls */
