language: cpp

os:
 - osx
 - linux
 
osx_image: xcode6.4

compiler:
 - clang
 
before_script:
 - mkdir build
 - cd build
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi;
 - brew install gnu-sed --with-default-names
 
script:
# - cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 ..
 - ../configure --enable-optimized --disable-bindings --enable-targets=host --enable-shared --enable-libffi
 - make -j4
 
after_success:
 - cat ./cmake/modules/LLVMConfig.cmake
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - clang-3.6
